"""refactor trustlens schema

Revision ID: 3bb432039262
Revises: 656024608ff8
Create Date: 2026-06-14 03:31:38.074133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb432039262'
down_revision: Union[str, Sequence[str], None] = '656024608ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.add_column('exports', sa.Column('job_id', sa.UUID(), nullable=False))
    op.add_column('exports', sa.Column('export_format', sa.String(length=20), nullable=False))
    op.alter_column('exports', 'file_path',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(op.f('exports_submission_id_fkey'), 'exports', type_='foreignkey')
    op.create_foreign_key(None, 'exports', 'analysis_jobs', ['job_id'], ['job_id'], ondelete='CASCADE')
    op.drop_column('exports', 'submission_id')
    op.drop_column('exports', 'export_type')
    op.add_column('metadata_checks', sa.Column('crossref_found', sa.Boolean(), nullable=False))
    op.add_column('metadata_checks', sa.Column('doi_valid', sa.Boolean(), nullable=False))
    op.add_column('metadata_checks', sa.Column('matched_authors', sa.Text(), nullable=True))
    op.add_column('metadata_checks', sa.Column('matched_year', sa.Integer(), nullable=True))
    op.add_column('metadata_checks', sa.Column('matched_source', sa.Text(), nullable=True))
    op.add_column('metadata_checks', sa.Column('publisher_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('metadata_checks', sa.Column('citation_count', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'metadata_checks', ['reference_id'])
    op.drop_constraint(op.f('metadata_checks_reference_id_fkey'), 'metadata_checks', type_='foreignkey')
    op.create_foreign_key(None, 'metadata_checks', 'references', ['reference_id'], ['reference_id'], ondelete='CASCADE')
    op.drop_column('metadata_checks', 'is_verified')
    op.drop_column('metadata_checks', 'provider')
    op.drop_column('metadata_checks', 'confidence_score')
    op.drop_column('metadata_checks', 'matched_doi')
    op.add_column('references', sa.Column('job_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('references_document_id_fkey'), 'references', type_='foreignkey')
    op.create_foreign_key(None, 'references', 'analysis_jobs', ['job_id'], ['job_id'], ondelete='CASCADE')
    op.drop_column('references', 'document_id')
    op.add_column('scores', sa.Column('job_id', sa.UUID(), nullable=False))
    op.add_column('scores', sa.Column('source_score', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('scores', sa.Column('citation_format_score', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('scores', sa.Column('classification', sa.String(length=50), nullable=False))
    op.add_column('scores', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('scores', 'recency_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('scores', 'relevance_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('scores', 'total_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.drop_constraint(op.f('scores_reference_id_key'), 'scores', type_='unique')
    op.create_unique_constraint(None, 'scores', ['job_id'])
    op.drop_constraint(op.f('scores_reference_id_fkey'), 'scores', type_='foreignkey')
    op.create_foreign_key(None, 'scores', 'analysis_jobs', ['job_id'], ['job_id'], ondelete='CASCADE')
    op.drop_column('scores', 'label')
    op.drop_column('scores', 'format_score')
    op.drop_column('scores', 'reference_id')
    op.drop_column('scores', 'authenticity_score')
    op.drop_column('scores', 'credibility_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('credibility_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('scores', sa.Column('authenticity_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('scores', sa.Column('reference_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('scores', sa.Column('format_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('scores', sa.Column('label', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.create_foreign_key(op.f('scores_reference_id_fkey'), 'scores', 'references', ['reference_id'], ['reference_id'])
    op.drop_constraint(None, 'scores', type_='unique')
    op.create_unique_constraint(op.f('scores_reference_id_key'), 'scores', ['reference_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('scores', 'total_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('scores', 'relevance_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('scores', 'recency_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.drop_column('scores', 'created_at')
    op.drop_column('scores', 'classification')
    op.drop_column('scores', 'citation_format_score')
    op.drop_column('scores', 'source_score')
    op.drop_column('scores', 'job_id')
    op.add_column('references', sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'references', type_='foreignkey')
    op.create_foreign_key(op.f('references_document_id_fkey'), 'references', 'documents', ['document_id'], ['document_id'])
    op.drop_column('references', 'job_id')
    op.add_column('metadata_checks', sa.Column('matched_doi', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('metadata_checks', sa.Column('confidence_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('metadata_checks', sa.Column('provider', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('metadata_checks', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'metadata_checks', type_='foreignkey')
    op.create_foreign_key(op.f('metadata_checks_reference_id_fkey'), 'metadata_checks', 'references', ['reference_id'], ['reference_id'])
    op.drop_constraint(None, 'metadata_checks', type_='unique')
    op.drop_column('metadata_checks', 'citation_count')
    op.drop_column('metadata_checks', 'publisher_score')
    op.drop_column('metadata_checks', 'matched_source')
    op.drop_column('metadata_checks', 'matched_year')
    op.drop_column('metadata_checks', 'matched_authors')
    op.drop_column('metadata_checks', 'doi_valid')
    op.drop_column('metadata_checks', 'crossref_found')
    op.add_column('exports', sa.Column('export_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('exports', sa.Column('submission_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exports', type_='foreignkey')
    op.create_foreign_key(op.f('exports_submission_id_fkey'), 'exports', 'submissions', ['submission_id'], ['submission_id'])
    op.alter_column('exports', 'file_path',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('exports', 'export_format')
    op.drop_column('exports', 'job_id')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
