"""add citations table

Revision ID: 9a7a3f5b5c1a
Revises: bf2048e8a2a1
Create Date: 2026-06-16 20:13:32.525958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7a3f5b5c1a'
down_revision: Union[str, Sequence[str], None] = 'bf2048e8a2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('reference_section_id', sa.UUID(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('detected_style', sa.String(length=50), nullable=False),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reference_section_id'], ['reference_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'sequence_no', name='uq_citations_submission_sequence')
    )
    op.create_index(op.f('ix_citations_reference_section_id'), 'citations', ['reference_section_id'], unique=False)
    op.create_index(op.f('ix_citations_submission_id'), 'citations', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citations_submission_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_reference_section_id'), table_name='citations')
    op.drop_table('citations')
    # ### end Alembic commands ###
