"""add metadata records table

Revision ID: bc6764b587e6
Revises: 9a7a3f5b5c1a
Create Date: 2026-06-16 20:26:38.895517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc6764b587e6'
down_revision: Union[str, Sequence[str], None] = '9a7a3f5b5c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('citation_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('query_type', sa.String(length=50), nullable=False),
    sa.Column('query_value', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('matched_title', sa.Text(), nullable=True),
    sa.Column('matched_year', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_records_citation_id'), 'metadata_records', ['citation_id'], unique=False)
    op.create_index(op.f('ix_metadata_records_submission_id'), 'metadata_records', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metadata_records_submission_id'), table_name='metadata_records')
    op.drop_index(op.f('ix_metadata_records_citation_id'), table_name='metadata_records')
    op.drop_table('metadata_records')
    # ### end Alembic commands ###
